apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-entry
  # ⚠️ 注意：命名空间必须与 namespace.yaml 中的 name 保持一致
  namespace: micro-demo
spec:
  ingressClassName: nginx
  rules:
    - host: micro.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-entry
                port:
                  number: 80

