apiVersion: v1
kind: Service
metadata:
  name: go-backend
  # ⚠️ 注意：命名空间必须与 namespace.yaml 中的 name 保持一致
  namespace: micro-demo
spec:
  selector:
    app: go-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080

